### ISSUE TITLE
User can view the company branding.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/sway-finance#1]
# Motivation
Users should immediately see company branding via a logo placed near the top of the page.

# Tasks
- [x] Create html and css files
- [x] Create element for page background
- [x] Create a directory for images to be used 
- [x] Add logo and background images to images directory
- [x] Add background image, position and size accordingly
- [x] Place logo on page within Bootstrap grid system
- [x] Add container for foreground content
- [x] Resize and position logo
