### ISSUE TITLE
User can view navigation links.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/sway-finance#3]
# Motivation

Links to important pages, including FAQ and Security, should be visible at the top of the page opposite the logo on the same line.

# Tasks

- [x] Create a header element to contain the logo and the eventual nav links.
- [x] Remove logo relative positioning offset
- [x] Add padding to top of header to position logo appropriately
- [x] Create two links with class="nav-link" containing appropriate text
- [x] Adjust position of the navigation links to the right side of page
- [x] Wrap link tags in existing "row" div to vertically align in header
- [x] Configure nav-link dimensions to include a box around the text
- [x] Adjust link font style
- [x] Increase nav-link margins to preserve horizontal alignment
- [x] Finalized header padding and logo position
- [x] Set nav-link text to added Google Font "Roboto"

**Comment by danielduffield** [comment]
![screen shot 2017-06-02 at 4 01 08 pm](https://cloud.githubusercontent.com/assets/29046343/26747743/c28a137c-47ac-11e7-8cc7-8fe9131a9dad.png)
