### ISSUE TITLE
User can read the product description.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/sway-finance#5]
# Motivation

Provide a large, eye-catching product description underneath the header.

# Tasks

- [x] Rename foreground-above-fold class to foreground for simplicity
- [x] Create a container for the product description
- [x] Add an H1 tag for the main description with the appropriate text, within the container
- [x] Add an H4 tag for the sub-level description with approp. text, within the container
- [x] Adjust the top padding to situate the description in the right spot
- [x] Change the text align in the product description container to center
- [x] Adjust the font family and color
- [x] Rename main-description id to description-container
- [x] Add classes to main-description and sub-description to h1 and h4 tags respectively
- [x] Finalize product description sizing, letter spacing, and font weight
