### ISSUE TITLE
User can view a screenshot of the Sway bot in Slack.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/sway-finance#7]
# Motivation

Provide users with a preview of the Slack bot in action, thereby demonstrating it's general feel and value.

# Tasks

- [x] Add product snapshot to images directory
- [x] Add product snapshot to page with id "slack-snapshot" and class "img-responsive"
- [x] Center image
- [x] Provide a min width property
- [x] Adjust top padding for proper image placement
